# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = XingLib
DESTDIR = ../lib
QT += core sql xml xmlpatterns axserver axcontainer widgets gui concurrent
CONFIG += staticlib debug
DEFINES += WIN64 QT_DLL QT_SQL_LIB QT_CONCURRENT_LIB QT_WIDGETS_LIB XINGLIB_LIB QT_XML_LIB QT_XMLPATTERNS_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug \
    ./Src/service/info \
    ./Src/service/chart/ui \
    ./Src/service/chart/setting
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(XingLib.pri)
