#ifndef LOG_H
#define LOG_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(xaSession)
Q_DECLARE_LOGGING_CATEGORY(xaQuery)
Q_DECLARE_LOGGING_CATEGORY(queryMngr)
Q_DECLARE_LOGGING_CATEGORY(loginMngr)
Q_DECLARE_LOGGING_CATEGORY(trQuery)
#endif // LOG_H
