# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = TraderX
DESTDIR = ../bin
QT += core sql axserver axcontainer widgets gui concurrent
CONFIG += debug
DEFINES += WIN64 QT_DLL QT_SQL_LIB QT_CONCURRENT_LIB QT_WIDGETS_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Debug
LIBS += -L"./../../../ChartDirector/lib" \
    -L"./../lib" \
    -lXingLib \
    -lchartdir60
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(TraderX.pri)
